### ISSUE TITLE
Setting Gain is preventing automatic Gain-Control

### ISSUE THREAD

**Issue by hwater** [openplotter/openplotter-sdr-vhf#1]
Hello

i use an RTL - Stick with automatic gain control, but having to set an value to the "AIS Settings"
disables it.

_Here is my tested Setting:_

/usr/bin/rtl_ais -d 0 -p 0 -P 10110
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Edge tuning disabled.
DC filter enabled.
RTL AGC disabled.
Internal AIS decoder enabled.
Buffer size: 163.84 mS
Downsample factor: 64
Low pass: 25000 Hz
Output: 48000 Hz
Found Rafael Micro R820T tuner
Log NMEA sentences to console OFF
AIS data will be sent to 127.0.0.1 port 10110
Tuner gain set to automatic.
Tuned to 162000000 Hz.
Sampling at 1600000 S/s.
Allocating 12 zero-copy buffers

_These are your "AIS Setting": the Gain-value can`t stay empty, so using zero here:_

/usr/bin/rtl_ais -d 0 -p 0 -g 0 -P 10110
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Edge tuning disabled.
DC filter enabled.
RTL AGC disabled.
Internal AIS decoder enabled.
Buffer size: 163.84 mS
Downsample factor: 64
Low pass: 25000 Hz
Output: 48000 Hz
Found Rafael Micro R820T tuner
Log NMEA sentences to console OFF
AIS data will be sent to 127.0.0.1 port 10110
Tuner gain set to 0.00 dB.
Tuned to 162000000 Hz.
Sampling at 1600000 S/s.
Allocating 12 zero-copy buffers

I would like to use this Feature of the Device, so please add an Checkbox to omit the "-g 0" 
from the openplotter-rtl_ais.service Routine. Maybe name the Checkbox "enable Automatic Tuner Gain" or do this hidden if the user leaves the Gain-value empty.
Of Couse, not every SDR-Stick has this automatic Feature, most of my old ones work with gain > 30.

Otherwise - Great Work,
Holger

**Comment by sailoog** [comment]
You are right. Maybe adding a text "leave blank to set auto" could work.

**Comment by hwater** [comment]
sounds okay, less disturbing to others.

**Comment by sailoog** [comment]
closed by https://github.com/openplotter/openplotter-sdr-vhf/commit/0e9872173335d562ea5f97408234e1e3771c38ab
