### ISSUE TITLE
AIS sentences not forwarded to SignalK

### ISSUE THREAD

**Issue by Jamos1988** [openplotter/openplotter-sdr-vhf#4]
Hi, SDR VHF works like a charm, but the connection in SignalK on UDP port 10110 receives nothing.
The strange thing is, OpenCPN with the same connection does receive AIS objects.
I've tried experimenting with Kplex in OP2, but there seems to be a bug in the connections. Cannot be applied or restarted (see topic https://forum.openmarine.net/showthread.php?tid=2421&highlight=can%27t+restart+kplex )

Basically I want the AIS objects to be visible in the Freeboard App in SignalK, I am trying to understand the connection that SDR VHF makes in the Openplotter-rtl_ais process. I presume this starts up the UDP 10110 port? Even without the Kplex connections OpenCPN will receive the AIS messages.  But, getting them to SignalK seems impossible at the moment. I hope you can point me in the right direction.

**Comment by Jamos1988** [comment]
In the mean time I've started a Kplex discussion at forum.openmarin.net, and although Kplex has issues it now seems to point more to SDR VHF and/or SignalK. See post at https://forum.openmarine.net/showthread.php?tid=2421&pid=14824#pid14824

No matter what port I configure in SDR VHF, no data is coming into SignalK. The NMEA183 UDP connection in Signalk is automatically created by SDR VHF, and when looking at Network and Addresses in the Network Plugin, I can see that the port is properly started. However, only openCPN will receive the data, and not SignalK.

So, I've been looking at an Openplotter 1 configuration that worked, and this was the configuration:

- Kplex system UDP in 10110
- Kplex signalk TCP out 30330
- NMEA 0183 TCP connection in SignalK port 10110
- OpenCPN TCP input 10110

The only difference is that SDR VHF creates a UDP connection in SignalK, and in Openplotter1 the incoming connection was TCP.
But, both don't work and dont show any deltas/second.

I've tried numerous combinations now, but I don't get any step further. Hope you can help!

Kind regards

**Comment by Jamos1988** [comment]
Some new information:

When the SignalK connection UDP 30330 is running, OpenCPN receives AIS. Without it, it doesn't.
SignalK does seem to passthrough the data to OpenCPN, but this is not visible in the Data Browser.

**Comment by sailoog** [comment]
You do not need kplex. Remove any network connection there to be sure you do not have conflicts.
OpenCPN must listen only to TCP localhost 10110. Remove any extra network connection.
Remove any signal k network connection to be sure you have not conflicts and use openplotter-sdr-vhf app to create the Signal k connection using the default UDP 10110 port or any of your election.
If opencpn is getting data means that signal k is getting data too. How do you check data in signal k? if you use the data browser be sure your are not filtering by "self" data.

**Comment by Jamos1988** [comment]
Thanks Sailoog,

I've done exactly as you said, removed all connections in SK. Only one default connection in OpenCPN.
To be expected, no data in OpenCPN.
Then, from the SDR VHF plugin, started the process on default 10110.
Checked SK and now a connection has been added.
To be expected, now there is AIS data in OpenCPN.
Then, in SK I am looking at the Data Browser, which has only two options: "please choose context"  and "self".
When choosing either of those, no AIS data is visible and maptracker and freeboard show no AIS data.

**Comment by sailoog** [comment]
OK, so if you have AIS data in opencpn you have data in Signal k server.
Wait until you can see AIS data in opencpn and then type this in your browser: http://localhost:3000/signalk/v1/api/vessels/
You should see AIS data there, if not go to signal k log to search for any error.

**Comment by Jamos1988** [comment]
Thanks, I did the check:

`{"urn:mrn:signalk:uuid:943fd5b9-ed14-4f26-8798-f9262882335f":{"uuid":"urn:mrn:signalk:uuid:943fd5b9-ed14-4f26-8798-f9262882335f","navigation":{"attitude":{"meta":{"description":"Vessel attitude: roll, pitch and yaw"},"value":{"roll":-0.015830136751000003,"pitch":0.0014660766120000001,"yaw":null},"$source":"OpenPlotter.I2C.pypilot","timestamp":"2020-07-16T11:51:07.972Z"},"position":{"meta":{"description":"The position of the vessel in 2 or 3 dimensions (WGS84 datum)"},"value":{"longitude":5.030568333333333,"latitude":52.63662},"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"courseOverGroundTrue":{"meta":{"units":"rad","description":"Course over ground (true)"},"value":2.7605872785097545,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"speedOverGround":{"meta":{"units":"m/s","description":"Vessel speed over ground. If converting from AIS 'HIGH' value, set to 102.2 (Ais max value) and add warning in notifications"},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"magneticVariation":{"meta":{"units":"rad","description":"The magnetic variation (declination) at the current position that must be added to the magnetic heading to derive the true heading. Easterly variations are positive and Westerly variations are negative (in Radians)."},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"magneticVariationAgeOfService":{"meta":{"units":"s","description":"Seconds since the 1st Jan 1970 that the variation calculation was made"},"value":1594900268,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"datetime":{"meta":{"description":"Time and Date from the GNSS Positioning System"},"value":"2020-07-16T11:51:08.000Z","$source":"OPgps.GP","timestamp":"2020-07-16T11:51:08.000Z","sentence":"RMC"},"courseOverGroundMagnetic":{"meta":{"units":"rad","description":"Course over ground (magnetic)"},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.283Z","sentence":"VTG"},"headingMagnetic":{"meta":{"units":"rad","description":"Current magnetic heading of the vessel, equals 'headingCompass adjusted for magneticDeviation'"},"value":1.407712761809969,"$source":"OPpypilot.AP","timestamp":"2020-07-16T11:51:07.738Z","sentence":"HDM"},"gnss":{"methodQuality":{"meta":{"description":"Quality of the satellite fix"},"value":"DGNSS fix","$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"},"satellites":{"meta":{"description":"Number of satellites"},"value":12,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"},"antennaAltitude":{"meta":{"units":"m","description":"Altitude of antenna"},"value":-21,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"},"horizontalDilution":{"meta":{"description":"Horizontal Dilution of Precision"},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"},"differentialAge":{"meta":{"units":"s","description":"Age of DGPS data"},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"},"differentialReference":{"meta":{"description":"ID of DGPS base station"},"value":0,"$source":"OPgps.GP","timestamp":"2020-07-16T11:51:07.000Z","sentence":"GGA"}},"courseGreatCircle":{"activeRoute":{"href":{"meta":{"description":"A reference (URL) to the presently active route, in resources."},"value":null,"$source":"freeboard-sk-helper","timestamp":"2020-07-16T11:50:53.021Z"},"startTime":{"meta":{"description":"The time this route was activated"},"value":null,"$source":"freeboard-sk-helper","timestamp":"2020-07-16T11:50:53.021Z"}},"nextPoint":{"position":{"value":null,"$source":"freeboard-sk-helper","timestamp":"2020-07-16T11:50:53.021Z"}}}},"electrical":{"batteries":{"system":{"current":{"meta":{"units":"A","description":"Current flowing out (+ve) or in (-ve) to the device"},"value":-0.2,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.743Z"},"power":{"value":-2.7,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.744Z"},"voltage":{"meta":{"units":"V","description":"Voltage measured at or as close as possible to the device"},"value":13.5,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.742Z"}},"ups":{"state":{"value":1,"$source":"signalk-node-red","timestamp":"2020-07-16T09:30:32.053Z"}}}},"notifications":{"electrical":{"batteries":{"system":{"voltage":{"meta":{"units":"V","description":"Voltage measured at or as close as possible to the device"},"value":{"state":"normal","timestamp":"2020-07-16T09:30:32.729Z","message":"The battery voltage is normal"},"$source":"simple-notifications","timestamp":"2020-07-16T09:30:32.730Z"}}}}},"environment":{"outside":{"temperature":{"meta":{"units":"K","description":"Current outside air temperature"},"value":45.1,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.442Z"},"pressure":{"meta":{"units":"Pa","description":"Current outside air ambient pressure"},"value":1021.18,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.443Z"}},"inside":{"humidity":{"meta":{"description":"This regex pattern is used for validation of the identifier for the environmental zone, eg. engineRoom, mainCabin, refrigerator"},"value":29.35,"$source":"signalk-node-red","timestamp":"2020-07-16T11:51:07.444Z"}}}}}`

Seems to have only self data, no AIS.

SignalK server log says:

`Jul 16 13:54:56 @signalk/aisreporter:aisreporter: mmsi missing in settings
Jul 16 13:55:02 signalk-server running at 0.0.0.0:[object Object]
Jul 16 13:55:02 /home/pi/.signalk/freeboard-sk-helper/grib - OK...
Jul 16 13:55:02 /home/pi/.signalk/resources - OK...
Jul 16 13:55:02 ** FS createSavePaths() **
Jul 16 13:55:02 /home/pi/.signalk/resources/routes - OK....
Jul 16 13:55:02 /home/pi/.signalk/resources/waypoints - OK....
Jul 16 13:55:02 /home/pi/.signalk/resources/notes - OK....
Jul 16 13:55:02 /home/pi/.signalk/resources/regions - OK....
Jul 16 13:55:02 Chart plugin: Found 0 charts from /home/pi/.signalk/charts
Jul 16 13:55:02 GET /admin/ 304 41.433 ms - -
Jul 16 13:55:03 GET /admin/ 304 31.857 ms - -
Jul 16 13:55:03 16 Jul 13:55:03 - [info] Welcome to Node-RED ===================
Jul 16 13:55:03 16 Jul 13:55:03 - [info] Node-RED version: v1.0.6
Jul 16 13:55:03 16 Jul 13:55:03 - [info] Node.js version: v10.19.0
Jul 16 13:55:03 16 Jul 13:55:03 - [info] Linux 4.19.97-v7+ arm LE
Jul 16 13:55:03 GET /admin/index.fonts.css 304 13.272 ms - -
Jul 16 13:55:03 GET /admin/index.styles.css 304 10.018 ms - -
Jul 16 13:55:03 GET /admin/index.bundle.js 304 3.570 ms - -
Jul 16 13:55:03 GET /vessel 304 22.755 ms - -
Jul 16 13:55:03 GET /loginStatus 200 5.140 ms - 210
Jul 16 13:55:03 GET /plugins 304 151.728 ms - -
Jul 16 13:55:03 GET /security/access/requests 304 4.882 ms - -
Jul 16 13:55:03 GET /admin/fonts/Simple-Line-Icons.0cb0b9c589c0624c9c78dd3d83e946f6.woff2 304 195.459 ms - -
Jul 16 13:55:03 GET /admin/fonts/fa-solid-900.55eb2a60e8181f0e68b558c991973bf0.woff2 304 17.093 ms - -
Jul 16 13:55:03 GET /webapps 304 110.922 ms - -
Jul 16 13:55:03 GET /signalk 304 109.333 ms - -
Jul 16 13:55:03 GET /admin/fonts/signal-k-logo-image-text.9fcbd4af20a13fb46f0c2ac6ef87b911.svg 304 6.828 ms - -
Jul 16 13:55:04 16 Jul 13:55:04 - [info] Loading palette nodes
Jul 16 13:55:07 16 Jul 13:55:07 - [info] Dashboard version 2.20.0 started at /plugins/signalk-node-red/redApi/ui
Jul 16 13:55:09 [object Object]
Jul 16 13:55:09 16 Jul 13:55:09 - [info] Context store : 'default' [module=memory]
Jul 16 13:55:09 16 Jul 13:55:09 - [info] User directory : /home/pi/.signalk/red
Jul 16 13:55:09 16 Jul 13:55:09 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
Jul 16 13:55:09 16 Jul 13:55:09 - [info] Flows file : /home/pi/.signalk/red/flows_openplotter.json
Jul 16 13:55:09 16 Jul 13:55:09 - [info] Starting flows
Jul 16 13:55:09 16 Jul 13:55:09 - [info] Started flows
Jul 16 13:55:09 0.01
Jul 16 13:55:09 false
Jul 16 13:55:09 initing!
Jul 16 13:55:10 GET /appstore/available 200 6871.736 ms - -
Jul 16 13:55:10 0.01
Jul 16 13:55:10 false
Jul 16 13:55:10 initing!`

The raw log says (with loggin on the sdr vhf connection):

`1594900429081;N;!AIVDM,1,1,,B,13`ekT0P00PG62<N7P5N4?wN2@Kw,0*7C
1594900429090;N;
1594900436161;N;!AIVDM,1,1,,B,13`jgKgP00PG:ebN7S<N4?wh2HPq,0*0B
1594900436161;N;
1594900437572;N;!AIVDM,1,1,,A,13`ekT0P01PG62DN7P4tW?wj2@Qe,0*72
1594900437573;N;
1594900448155;N;!AIVDM,1,1,,B,13`ekT0P00PG62BN7P5>4?v@2D5L,0*3C
1594900448155;N;
1594900452586;N;!AIVDM,1,1,,B,13aFgC@P00PG;FvN7agKQOvH287G,0*46
1594900452586;N;
1594900455538;N;!AIVDM,1,1,,B,13`jgKgP00PG:ebN7S<>4?vN2<0f,0*5F
1594900455538;N;
1594900458818;N;!AIVDM,1,1,,A,13`ekT0P00PG62:N7P4v4?vT2<5O,0*61
1594900458819;N;
1594900464893;N;!AIVDM,1,1,,A,13`jgKgP00PG:ebN7S<>4?vh20T4,0*40
1594900464894;N;
1594900467925;N;!AIVDM,1,1,,B,13`ekT0P00PG62@N7P5>4?vn25KH,0*1B
1594900467926;N;
1594900473745;N;!AIVDM,1,1,,B,13aFgC@P00PG;FvN7agKQOw22@Cg,0*11
1594900473746;N;
1594900475408;N;!AIVDM,1,1,,A,13aL<FwP00PG:sfN7TF00?w625KH,0*7D
1594900475409;N;
1594900485465;N;!AIVDM,1,1,,A,13`jgKgP00PG:ebN7S<N4?wJ20SD,0*64
1594900485465;N;
1594900509233;N;!AIVDM,1,1,,A,13`jgKgP00PG:ebN7S<>4?v<2<0f,0*2E
1594900509242;N;
1594900509243;N;!AIVDM,1,1,,B,13`ekT0P00PG62BN7P5>4?v@2@4g,0*12
1594900509243;N;
1594900516572;N;!AIVDM,1,1,,A,13aL<FwP00PG:sDN7TK00?vP2D5l,0*1E
1594900516573;N;
1594900518867;N;!AIVDM,1,1,,A,33`ekT0P00PG62HN7P5v4?vT2?5Q,0*0D
1594900518868;N;
1594900526498;N;!AIVDM,1,1,,A,13`jgKgP00PG:ebN7S<>4?vl2D0g,0*07
1594900526499;N;
1594900526582;N;!AIVDM,1,1,,B,13aL<FwP00PG:sBN7TJP0?vl25KL,0*69
1594900526583;N;
1594900533791;N;!AIVDM,1,1,,B,13aFgC@P00PG;FvN7agKQOw22<3w,0*0D
1594900533793;N;
1594900535349;N;!AIVDM,1,1,,A,13aL<FwP00PG:s>N7TJh0?w620T;,0*18
1594900535350;N;
1594900538375;N;!AIVDM,1,1,,A,13`ekT0P00PG62HN7P6>4?w<20SC,0*56
1594900538375;N;
1594900545678;N;!AIVDM,1,1,,A,13`jgKgP00PG:ebN7S<>4?wJ2@Jg,0*5E
1594900545680;N;
1594900566160;N;!AIVDM,1,1,,A,13`jgKgP00PG:edN7S<>4?v<283S,0*1A
1594900566161;N;
1594900568129;N;!AIVDM,1,1,,B,13`ekT0P00PG62<N7P7>4?v@2<5Q,0*25
1594900568129;N;
1594900572645;N;!AIVDM,1,1,,B,13aFgC@P00PG;FvN7agKQOvH20Sj,0*07
1594900572646;N;
1594900588126;N;!AIVDM,1,1,,B,13`ekT0P00PG620N7P7>4?vp2L5S,0*6B
1594900588127;N;
1594900596576;N;!AIVDM,1,1,,B,33`jgKgP00PG:edN7S<>4?w82@9Q,0*6E
1594900596576;N;
`

**Comment by sailoog** [comment]
I can not see anything abnormal. This is really strange, I will try to reproduce it.

@tkurki any idea?

**Comment by Jamos1988** [comment]
Not sure if this helps:

**Freeboard log:**

`Jul 16 16:01:14 GET /signalk/v1/api/vessels/self/navigation/courseGreatCircle/activeRoute 404 38.197 ms - 207
Jul 16 16:01:14 GET /signalk/v1/api/vessels/self/navigation/anchor 404 26.696 ms - 184
Jul 16 16:01:14 GET /signalk/v1/api/resources/routes 304 42.844 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/vessels/self 200 43.395 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/resources/waypoints 304 15.093 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/vessels/self/navigation/courseGreatCircle/activeRoute 404 33.216 ms - 207
Jul 16 16:01:14 GET /signalk/v1/api/resources/regions?position=52.63054980928521,5.090971992014943&dist=20 304 14.835 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/resources/notes?position=52.63054980928521,5.090971992014943&dist=20 304 6.896 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/resources/grib 304 8.937 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/resources/charts 304 104.034 ms - -
Jul 16 16:01:14 GET /signalk/v1/api/vessels/self/navigation/anchor 404 43.187 ms - 184
Jul 16 16:01:14 GET /signalk/v1/api/resources/routes 304 13.768 ms - -`

**Maptracker log:**

`Jul 16 16:02:05 GET /@signalk/maptracker 301 16.390 ms - 205
Jul 16 16:02:05 GET /@signalk/maptracker/ 200 10.182 ms - -
Jul 16 16:02:05 GET /@signalk/maptracker/bower_components/Leaflet.Easybutton/src/easy-button.css 404 22.307 ms - 214
Jul 16 16:02:05 GET /@signalk/maptracker/bower_components/Leaflet.EasyButton/src/easy-button.js 200 41.518 ms - -
Jul 16 16:02:05 GET /@signalk/maptracker/bower_components/components-font-awesome/css/font-awesome.css 200 37.715 ms - -
Jul 16 16:02:05 GET /@signalk/maptracker/bower_components/leaflet/dist/leaflet.css 200 35.021 ms - -
Jul 16 16:02:05 GET /@signalk/maptracker/dist/map.js 200 52.969 ms - -
Jul 16 16:02:05 GET /signalk/v1/api/resources/charts 304 14.158 ms - -
Jul 16 16:02:05 GET /@signalk/maptracker/FFFFFF-0.6.png 200 34.984 ms - 68
Jul 16 16:02:05 GET /signalk/v1/api/self 200 5.002 ms - 67`

**Comment by Jamos1988** [comment]
OMG I've found it! It seems to be caused by the AIS forwarder plugin I use for reporting to Marinetraffic. The strange thing is, in OP1 with exactly the same version Signalk and plugin, it works. But, in OP2 with exactly the same version, it doesn't. I even have the exact same signalk configuration.

I don't understand what the difference is...

**Comment by tkurki** [comment]
Mystery solved! Now I would like to know the exact mechanism to prevent this in the future. Can you share the plugin’s configuration from under $HOME/.signalk/plugin-config-data ?

**Comment by Jamos1988** [comment]
Yes, that's:

`{
  "enabled": true,
  "enableLogging": false,
  "enableDebug": false,
  "configuration": {
    "endpoints": [
      {
        "ipaddress": "5.9.207.224",
        "port": 10517
      }
    ],
    "updaterate": 60,
    "staticupdaterate": 360
  }
}`

**Comment by Jamos1988** [comment]
Ok, I've figured it out. When using a "non existent" or "faulty" port in this plugin, it blocks the AIS sentences for SignalK (Freeboard) usage, eventhough this port might be external. So, it seems if this plug-in is incorrectly configured then it stops traffic to "internal" signalk ports for some reason (but not opencpn?). I guess this could be prevented by using a field input mask, or some sort of tooltip saying something like "wrong port range",  or a test button that can verify the connection?

**Comment by tkurki** [comment]
That looks like config for Aisreporter, not Ais Forwarder - two different plugins.

**Comment by Jamos1988** [comment]
I thought I had to use both, because not only I wanted to report my self position but also share other's position with marinetraffic. It was my experience that I had to have them both to accomplish that, but maybe this is false. I'll test again if AIS reporter also sends self + other vessels.

**Comment by tkurki** [comment]
Aisreporter only reports self, was just wondering which caused your problem.
